import { User } from "@/services/api";

export const performanceValues = [50, 66, 61, 80, 75, 90];
export const performanceLabels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"];

export const tournaments = [
  {
    id: "global-tennis-open",
    category: "Tennis",
    title: "Global Tennis Open",
    dates: "Oct 15-20, 2025",
    location: "France",
    badge: "Elite",
    image: "https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "international-track-meet",
    category: "Athletics",
    title: "International Track Meet",
    dates: "Nov 2-5, 2025",
    location: "Germany",
    badge: "Pro",
    image: "https://images.unsplash.com/photo-1542728928-1413d1894ed1?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "euro-hoops-classic",
    category: "Basketball",
    title: "Euro Hoops Classic",
    dates: "Dec 10-15, 2025",
    location: "Spain",
    badge: "Champ",
    image: "https://images.unsplash.com/photo-1519861531473-9200262188bf?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "ocean-swim-series",
    category: "Swimming",
    title: "Ocean Swim Series",
    dates: "Jan 20-24, 2026",
    location: "Australia",
    badge: "Elite",
    image: "https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "summer-t20-series",
    category: "Cricket",
    title: "Summer T20 Series",
    dates: "Feb 5-12, 2026",
    location: "India",
    badge: "International",
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=1200&q=80",
  },
];

export const networkUsers: User[] = [
  {
    _id: "demo-network-1",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    country: "USA",
    email: "marcus@scoutx.app",
    name: "Marcus Aurelius",
    rating: 91,
    role: "scout",
    sport: "Basketball",
    position: "Coach",
  },
  {
    _id: "demo-network-2",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    country: "USA",
    email: "serena@scoutx.app",
    name: "Serena Vance",
    rating: 88,
    role: "athlete",
    sport: "Tennis",
    position: "Athlete",
  },
  {
    _id: "demo-network-3",
    avatar: "https://randomuser.me/api/portraits/men/46.jpg",
    country: "China",
    email: "david@scoutx.app",
    name: "David Chen",
    rating: 86,
    role: "scout",
    sport: "Football",
    position: "Scout",
  },
  {
    _id: "demo-network-4",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    country: "Germany",
    email: "elena@scoutx.app",
    name: "Elena Rostova",
    rating: 84,
    role: "athlete",
    sport: "Athletics",
    position: "Athlete",
  },
  {
    _id: "demo-network-5",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    country: "Australia",
    email: "michael@scoutx.app",
    name: "Michael Phelps Jr.",
    rating: 90,
    role: "athlete",
    sport: "Swimming",
    position: "Athlete",
  },
  {
    _id: "demo-network-6",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    country: "USA",
    email: "james@scoutx.app",
    name: "James Harden",
    rating: 89,
    role: "athlete",
    sport: "Basketball",
    position: "Athlete",
  },
];
